### PR TITLE
Darkmode fix

### LINKED ISSUE #6: Dark mode has issues
image
dark-mode has some issues

_Originally posted by @toratalet in https://github.com/T-Ev/TwitterSearchTokenTest/issues/5#issuecomment-1326074415_

### PR DESCRIPTION
**Pull request by T-Ev**

### CODE REVIEW

File: script.js [hunk 1]
```diff
@@ -185,10 +185,15 @@ const search = {
...
+    search.checkDarkMode();
+  },
+  checkDarkMode: () => {
     //check for darkmode
-    if (document.querySelector("body").style.backgroundColor !== "rgb(255, 255, 255)") {
-      search.listBox().classList.add("darkmode");
+    if (document.querySelector("body").style.backgroundColor !== "rgb(255, 255, 255)" && document.querySelector("body").style.backgroundColor !== "#FFFFFF") {
       document.querySelector(".filter-wrapper").classList.add("darkmode");
+      try {
+        search.listBox().classList.add("darkmode");
```
Comment (toratalet) [inline script.js:195]: Not fan of `try{} catch{}` as a work around, but it is working fine

**Review by toratalet — APPROVED** [review]
